listen_addresses = '*'
port = 5432
max_connections = 500

shared_buffers = 32GB
effective_cache_size = 160GB
maintenance_work_mem = 4GB
work_mem = 32MB

checkpoint_timeout = 15min
max_wal_size = 64GB
min_wal_size = 4GB
wal_compression = on

random_page_cost = 1.1
effective_io_concurrency = 256

log_min_duration_statement = 1000
log_checkpoints = on
log_connections = off
log_disconnections = off
log_lock_waits = on

autovacuum = on
autovacuum_max_workers = 6
autovacuum_naptime = 10s
