bind 0.0.0.0
port 6379
protected-mode yes
requirepass ${REDIS_PASSWORD}

maxmemory 7gb
maxmemory-policy allkeys-lru

appendonly yes
appendfsync everysec
save 900 1
save 300 10
save 60 10000

tcp-keepalive 300
timeout 0
